package lab1.mybatis.model;

public class City {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.CITY.ID
     *
     * @mbg.generated Fri Mar 04 14:14:56 EET 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.CITY.COUNTRY_NAME
     *
     * @mbg.generated Fri Mar 04 14:14:56 EET 2022
     */
    private String countryName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.CITY.NAME
     *
     * @mbg.generated Fri Mar 04 14:14:56 EET 2022
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.CITY.ID
     *
     * @return the value of PUBLIC.CITY.ID
     *
     * @mbg.generated Fri Mar 04 14:14:56 EET 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.CITY.ID
     *
     * @param id the value for PUBLIC.CITY.ID
     *
     * @mbg.generated Fri Mar 04 14:14:56 EET 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.CITY.COUNTRY_NAME
     *
     * @return the value of PUBLIC.CITY.COUNTRY_NAME
     *
     * @mbg.generated Fri Mar 04 14:14:56 EET 2022
     */
    public String getCountryName() {
        return countryName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.CITY.COUNTRY_NAME
     *
     * @param countryName the value for PUBLIC.CITY.COUNTRY_NAME
     *
     * @mbg.generated Fri Mar 04 14:14:56 EET 2022
     */
    public void setCountryName(String countryName) {
        this.countryName = countryName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.CITY.NAME
     *
     * @return the value of PUBLIC.CITY.NAME
     *
     * @mbg.generated Fri Mar 04 14:14:56 EET 2022
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.CITY.NAME
     *
     * @param name the value for PUBLIC.CITY.NAME
     *
     * @mbg.generated Fri Mar 04 14:14:56 EET 2022
     */
    public void setName(String name) {
        this.name = name;
    }
}