package lab1.mybatis.model;

import java.util.Set;

public class City {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.CITY.ID
     *
     * @mbg.generated Thu Mar 24 09:45:55 EET 2022
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.CITY.COUNTRY_NAME
     *
     * @mbg.generated Thu Mar 24 09:45:55 EET 2022
     */
    private String countryName1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.CITY.FULL_CITY_NAME
     *
     * @mbg.generated Thu Mar 24 09:45:55 EET 2022
     */
    private String fullCityName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.CITY.NAME
     *
     * @mbg.generated Thu Mar 24 09:45:55 EET 2022
     */
    private String name;

    private Set<StoreNetwork> storeNetworks;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.CITY.ID
     *
     * @return the value of PUBLIC.CITY.ID
     * @mbg.generated Thu Mar 24 09:45:55 EET 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.CITY.ID
     *
     * @param id the value for PUBLIC.CITY.ID
     * @mbg.generated Thu Mar 24 09:45:55 EET 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.CITY.COUNTRY_NAME
     *
     * @return the value of PUBLIC.CITY.COUNTRY_NAME
     * @mbg.generated Thu Mar 24 09:45:55 EET 2022
     */
    public String getCountryName1() {
        return countryName1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.CITY.COUNTRY_NAME
     *
     * @param countryName1 the value for PUBLIC.CITY.COUNTRY_NAME
     * @mbg.generated Thu Mar 24 09:45:55 EET 2022
     */
    public void setCountryName1(String countryName1) {
        this.countryName1 = countryName1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.CITY.FULL_CITY_NAME
     *
     * @return the value of PUBLIC.CITY.FULL_CITY_NAME
     * @mbg.generated Thu Mar 24 09:45:55 EET 2022
     */
    public String getFullCityName() {
        return fullCityName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.CITY.FULL_CITY_NAME
     *
     * @param fullCityName the value for PUBLIC.CITY.FULL_CITY_NAME
     * @mbg.generated Thu Mar 24 09:45:55 EET 2022
     */
    public void setFullCityName(String fullCityName) {
        this.fullCityName = fullCityName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.CITY.NAME
     *
     * @return the value of PUBLIC.CITY.NAME
     * @mbg.generated Thu Mar 24 09:45:55 EET 2022
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.CITY.NAME
     *
     * @param name the value for PUBLIC.CITY.NAME
     * @mbg.generated Thu Mar 24 09:45:55 EET 2022
     */
    public void setName(String name) {
        this.name = name;
    }

    public Set<StoreNetwork> getStoreNetworks() {
        return storeNetworks;
    }

    public void setStoreNetworks(Set<StoreNetwork> storeNetworks) {
        this.storeNetworks = storeNetworks;
    }
}