package lab1.mybatis.dao;

import java.util.List;
import lab1.mybatis.model.StoreNetwork;
import org.mybatis.cdi.Mapper;

@Mapper
public interface StoreNetworkMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.STORE_NETWORK
     *
     * @mbg.generated Fri Mar 04 14:14:56 EET 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.STORE_NETWORK
     *
     * @mbg.generated Fri Mar 04 14:14:56 EET 2022
     */
    int insert(StoreNetwork record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.STORE_NETWORK
     *
     * @mbg.generated Fri Mar 04 14:14:56 EET 2022
     */
    StoreNetwork selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.STORE_NETWORK
     *
     * @mbg.generated Fri Mar 04 14:14:56 EET 2022
     */
    List<StoreNetwork> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.STORE_NETWORK
     *
     * @mbg.generated Fri Mar 04 14:14:56 EET 2022
     */
    int updateByPrimaryKey(StoreNetwork record);
}