package lab1.mybatis.dao;

import lab1.mybatis.model.Store;
import org.mybatis.cdi.Mapper;

import java.util.List;

@Mapper
public interface StoreMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.STORE
     *
     * @mbg.generated Fri Mar 04 14:14:56 EET 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.STORE
     *
     * @mbg.generated Fri Mar 04 14:14:56 EET 2022
     */
    int insert(Store record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.STORE
     *
     * @mbg.generated Fri Mar 04 14:14:56 EET 2022
     */
    Store selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.STORE
     *
     * @mbg.generated Fri Mar 04 14:14:56 EET 2022
     */
    List<Store> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.STORE
     *
     * @mbg.generated Fri Mar 04 14:14:56 EET 2022
     */
    int updateByPrimaryKey(Store record);
}