package psk.mybatis.dao;

import psk.mybatis.model.City;
import org.mybatis.cdi.Mapper;

import java.util.List;
import java.util.Set;

@Mapper
public interface CityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.CITY
     *
     * @mbg.generated Fri Mar 04 14:14:56 EET 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.CITY
     *
     * @mbg.generated Fri Mar 04 14:14:56 EET 2022
     */
    int insert(City record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.CITY
     *
     * @mbg.generated Fri Mar 04 14:14:56 EET 2022
     */
    City selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.CITY
     *
     * @mbg.generated Fri Mar 04 14:14:56 EET 2022
     */
    List<City> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.CITY
     *
     * @mbg.generated Fri Mar 04 14:14:56 EET 2022
     */
    int updateByPrimaryKey(City record);

    Set<City> selectStoreNetworksInCity(int cityId);
}